<?php
/**
 * Файл конфигурации типов MIME.
 * 
 * @link https://www.iana.org/assignments/media-types/media-types.xhtml Media Types
 * @link https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types
 * 
 * @link https://rosgear.ru/
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */

return [
    'aac'  => ['document' => 'AAC audio', 'mime' => 'audio/aac', 'type' => 'audio'],
    'abw'  => ['document' => 'AbiWord document', 'mime' => 'application/x-abiword', 'type' => 'text'],
    'arc'  => ['document' => 'Archive document (multiple files embedded)', 'mime' => 'application/x-freearc', 'type' => 'archive'],
    'avi'  => ['document' => 'AVI: Audio Video Interleave', 'mime' => 'video/x-msvideo', 'type' => 'video'],
    'azw'  => ['document' => 'Amazon Kindle eBook format', 'mime' => 'application/vnd.amazon.ebook', 'type' => 'ebook'],
    'bin'  => ['document' => 'Any kind of binary data', 'mime' => 'application/octet-stream', 'type' => 'stream'],
    'bmp'  => ['document' => 'Windows OS/2 Bitmap Graphics', 'mime' => 'image/bmp', 'type' => 'image'],
    'bz'   => ['document' => 'BZip archive', 'mime' => 'application/x-bzip', 'type' => 'archive'],
    'bz2'  => ['document' => 'BZip2 archive', 'mime' => 'application/x-bzip2', 'type' => 'archive'],
    'csh'  => ['document' => 'C-Shell script', 'mime' => 'application/x-csh', 'type' => 'script'],
    'css'  => ['document' => 'Cascading Style Sheets (CSS)', 'mime' => 'text/css', 'type' => 'script'],
    'csv'  => ['document' => 'Comma-separated values (CSV)', 'mime' => 'text/csv', 'type' => 'text'],
    'doc'  => ['document' => 'Microsoft Word', 'mime' => 'application/msword', 'type' => 'ms'],
    'docx' => ['document' => 'Microsoft Word (OpenXML)', 'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'type' => 'ms'],
    'eot'  => ['document' => 'MS Embedded OpenType fonts', 'mime' => 'application/vnd.ms-fontobject', 'type' => 'font'],
    'epub' => ['document' => 'Electronic publication (EPUB)', 'mime' => 'application/epub+zip', 'type' => 'archive'],
    'gz'   => ['document' => 'GZip Compressed Archive', 'mime' => 'application/gzip', 'type' => 'archive'],
    'tgz'  => ['document' => 'GZip Compressed Archive', 'mime' => 'application/gzip', 'type' => 'archive'],
    'gif'  => ['document' => 'Graphics Interchange Format (GIF)', 'mime' => 'image/gif', 'type' => 'image'],
    'htm'  => ['document' => 'HyperText Markup Language (HTML)', 'mime' => 'text/html', 'type' => 'script'],
    'html' => ['document' => 'HyperText Markup Language (HTML)', 'mime' => 'text/html', 'type' => 'script'],
    'ico'  => ['document' => 'Icon format', 'mime' => 'image/vnd.microsoft.icon', 'type' => 'image'],
    'ics'  => ['document' => 'iCalendar format', 'mime' => 'text/calendar', 'type' => 'text'],
    'jar'  => ['document' => 'Java Archive (JAR)', 'mime' => 'application/java-archive', 'type' => 'archive'],
    'jpeg' => ['document' => 'JPEG images', 'mime' => 'image/jpeg', 'type' => 'image'],
    'jpg'  => ['document' => 'JPEG images', 'mime' => 'image/jpeg', 'type' => 'image'],
    'js'   => ['document' => 'JavaScript', 'mime' => 'text/javascript', 'type' => 'script'],
    'json' => ['document' => 'JSON format', 'mime' => 'application/json', 'type' => 'script'],
    'jsonld' => ['document' => 'JSON-LD format', 'mime' => 'application/ld+json', 'type' => 'script'],
    'mid'  => ['document' => 'Musical Instrument Digital Interface (MIDI)', 'mime' => 'audio/midi audio/x-midi', 'type' => 'audio'],
    'midi' => ['document' => 'Musical Instrument Digital Interface (MIDI)', 'mime' => 'audio/midi audio/x-midi', 'type' => 'audio'],
    'mjs'  => ['document' => 'JavaScript module', 'mime' => 'text/javascript', 'type' => 'script'],
    'mp3'  => ['document' => 'MP3 audio', 'mime' => 'audio/mpeg', 'type' => 'audio'],
    'mpeg' => ['document' => 'MPEG Video', 'mime' => 'video/mpeg', 'type' => 'video'],
    'mpkg' => ['document' => 'Apple Installer Package', 'mime' => 'application/vnd.apple.installer+xml', 'type' => 'apple'],
    'odp'  => ['document' => 'OpenDocument presentation document', 'mime' => 'application/vnd.oasis.opendocument.presentation', 'type' => 'open'],
    'ods'  => ['document' => 'OpenDocument spreadsheet document', 'mime' => 'application/vnd.oasis.opendocument.spreadsheet', 'type' => 'open'],
    'odt'  => ['document' => 'OpenDocument text document', 'mime' => 'application/vnd.oasis.opendocument.text', 'type' => 'open'],
    'oga'  => ['document' => 'OGG audio', 'mime' => 'audio/ogg', 'type' => 'audio'],
    'ogv'  => ['document' => 'OGG video', 'mime' => 'video/ogg', 'type' => 'video'],
    'ogx'  => ['document' => 'OGG', 'mime' => 'application/ogg', 'type' => 'ogg'],
    'opus' => ['document' => 'Opus audio', 'mime' => 'audio/opus', 'type' => 'audio'],
    'otf'  => ['document' => 'OpenType font', 'mime' => 'font/otf', 'type' => 'font'],
    'png'  => ['document' => ' Portable Network Graphics', 'mime' => 'image/png', 'type' => 'image'],
    'pdf'  => ['document' => 'Adobe Portable Document Format (PDF)', 'mime' => 'application/pdf', 'type' => 'pdf'],
    'phtml' => ['document' => 'Hypertext Preprocessor (Personal Home Page)', 'mime' => 'application/php', 'type' => 'script'],
    'php'  => ['document' => 'Hypertext Preprocessor (Personal Home Page)', 'mime' => 'application/php', 'type' => 'script'],
    'ppt'  => ['document' => 'Microsoft PowerPoint', 'mime' => 'application/vnd.ms-powerpoint', 'type' => 'ms'],
    'pptx' => ['document' => 'Microsoft PowerPoint (OpenXML)', 'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'type' => 'ms'],
    'rar'  => ['document' => 'RAR archive', 'mime' => ['application/vnd.rar', 'application/x-rar'], 'type' => 'archive'],
    'rtf'  => ['document' => 'Rich Text Format (RTF)', 'mime' => ['application/rtf', 'text/rtf'], 'type' => 'text'],
    'sh'   => ['document' => 'Bourne shell script', 'mime' => 'application/x-sh', 'type' => 'script'],
    'svg'  => ['document' => 'Scalable Vector Graphics (SVG)', 'mime' => 'image/svg+xml', 'type' => 'image'],
    'swf'  => ['document' => 'Small web format (SWF) or Adobe Flash document', 'mime' => 'application/x-shockwave-flash', 'type' => 'flash'],
    'tar'  => ['document' => 'Tape Archive (TAR)', 'mime' => 'application/x-tar', 'type' => 'archive'],
    'tif'  => ['document' => 'Tagged Image File Format (TIFF)', 'mime' => 'image/tiff', 'type' => 'image'],
    'tiff' => ['document' => 'Tagged Image File Format (TIFF)', 'mime' => 'image/tiff', 'type' => 'image'],
    'ts'   => ['document' => 'MPEG transport stream', 'mime' => 'video/mp2t', 'type' => 'video'],
    'ttf'  => ['document' => 'TrueType Font', 'mime' => 'font/ttf', 'type' => 'font'],
    'txt'  => ['document' => 'Text, (generally ASCII or ISO 8859-n)', 'mime' => 'text/plain', 'type' => 'text'],
    'md'   => ['document' => 'Markdown', 'mime' => 'text/markdown', 'type' => 'text'],
    'vsd'  => ['document' => 'Microsoft Visio', 'mime' => 'application/vnd.visio', 'type' => 'ms'],
    'wav'  => ['document' => 'Waveform Audio Format', 'mime' => 'audio/wav', 'type' => 'audio'],
    'weba' => ['document' => 'WEBM audio', 'mime' => 'audio/webm', 'type' => 'audio'],
    'webm' => ['document' => 'WEBM video', 'mime' => 'video/webm', 'type' => 'video'],
    'webp' => ['document' => 'WEBP image', 'mime' => 'image/webp', 'type' => 'image'],
    'woff' => ['document' => 'Web Open Font Format (WOFF)', 'mime' => 'font/woff', 'type' => 'font'],
    'woff2' => ['document' => 'Web Open Font Format (WOFF)', 'mime' => 'font/woff2', 'type' => 'font'],
    'xhtml' => ['document' => 'XHTML', 'mime' => 'application/xhtml+xml', 'type' => 'script'],
    'xls'  => ['document' => 'Microsoft Excel', 'mime' => 'application/vnd.ms-excel', 'type' => 'ms'],
    'xlsx' => ['document' => 'Microsoft Excel (OpenXML)', 'mime' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'type' => 'ms'],
    'xml'  => ['document' => 'XML', 'mime' => 'application/xml', 'type' => 'script'],
    'xul'  => ['document' => 'XUL', 'mime' => 'application/vnd.mozilla.xul+xml', 'type' => 'script'],
    'zip'  => ['document' => 'ZIP archive', 'mime' => 'application/zip', 'type' => 'archive'],
    'gpk'  => ['document' => 'Gear Service Pack', 'mime' => 'application/zip', 'type' => 'archive'],
    '3gp'  => ['document' => '3GPP audio/video container', 'mime' => 'video/3gpp', 'type' => 'video'],
    '3g2'  => ['document' => '3GPP2 audio/video container', 'mime' => 'video/3gpp2', 'type' => 'video'],
    '7z'   => ['document' => '7-zip archive', 'mime' => 'application/x-7z-compressed', 'type' => 'archive']
];
