<?php
use Ge\Helper\Str;
use Ge\Helper\Url;
use Ge\Panel\Helper\Ext;
use Ge\Panel\Helper\HtmlNavigator as HtmlNav;
?>
<div class="container-fluid">
    <div class="row-fluid">
        <h1>Информация о расширении модуля: <span>&laquo;<?= $name ?>&raquo;</span>
<?php
if ($baseRoute && $use === BACKEND):
    echo HtmlNav::linkIcon(
        'link', 19, 
        ['onclick' => Ext::jsAppWidgetLoad('@backend/' . $baseRoute), 'title' => 'Просмотреть']
    );
endif;
if ($baseRoute && $use === FRONTEND):
    echo HtmlNav::linkIcon(
        'link', 19, 
        ['href' => Url::to($baseRoute), 'target' => '_blank', 'title' => 'Просмотреть']
    );
endif;
?>
    </h1>
        <div class="icon" style="background-image: url(<?= $icon ?>)">
            <p><?= $description ?></p>
        </div>
    </div>
</div>

<?php if ($version) : ?>
<div class="row-fluid">
    <div class="col-md-12">
        <h2>Версия расширения</h2>
        <p>
            <label>Версия:</label>  
            <span class="parameter"><?= $version['version'] ?: '[ неизвестно ]' ?></span>
        </p>
        <p>
            <label>Дата:</label>  
            <span class="parameter"><?= $version['versionDate'] ? Ge::$app->formatter->toDate($version['versionDate']) : '[ неизвестно ]' ?></span>
        </p>
        <p>
            <label>Страница расширения:</label> 
<?php if ($version['url']): ?>
            <span class="parameter"><a target="_blank" href="<?= $version['url'] ?>"><?= $version['url'] ?></a></span>
<?php else: ?>
            <span class="parameter">[ неизвестно ]</span>
<?php endif ?>
        </p>
        <p>
            <label>Страница</label> 
            <a target="_blank" href="#" onclick="<?= Ext::jsAppWidgetLoad('@backend/marketplace/catalog/component/view', ['id' => $id]) ?>;return false">в кателоге Маркетплейс</a>
        </p>

        <h2>Автор</h2>
        <p>
            <label>Имя автора:</label> 
            <span class="parameter"><?= $version['author'] ?: '[ неизвестно ]' ?></span>
        </p>
        <p>
            <label>Страница автора:</label>
<?php if ($version['authorUrl']): ?>
            <span class="parameter"><a target="_blank" href="<?= $version['authorUrl'] ?>"><?= $version['authorUrl'] ?></a></span>
<?php else: ?>
            <span class="parameter">[ неизвестно ]</span>
<?php endif ?>
        </p>
        <p>
            <label>E-mail:</label> 
            <span class="parameter"><?= $version['email'] ?: '[ неизвестно ]' ?></span>
        </p>

        <h2>Лицензия</h2>
        <p>
<?php if ($version['licenseUrl']): ?>
            <span class="parameter"><a href="<?= $version['licenseUrl'] ?>"><?= $version['license'] ?></a></span>
<?php else: ?>
            <span class="parameter"><?= $version['license'] ?: '[ неизвестно ]' ?></span>
<?php endif ?>
        </p>
    </div>
</div>
<?php endif ?>

<div class="row-fluid">
    <div class="col-md-12">
        <h2>Состояние расширения</h2>
        <p>
            <label>Доступно:</label> <?= HtmlNav::checkIcon($enabled, 18) ?>
        </p>
    </div>
</div>

<div class="row-fluid">
    <div class="col-md-12">
        <h2>Расширение установлено</h2>
        <p>
            <label>Дата и время:</label> 
            <span class="parameter"><?= $createdDate ?: '[ неизвестно ]' ?></span>
        </p>
        <p>
            <label>Пользователь:</label> 
            <span class="parameter">
<?php
    if ($createdUser): 
        if (empty($createdUser['profile']['name'])):
            if (empty($createdUser['user']['username'])):
                echo '[ неизвестно ]';
            else:
                echo HtmlNav::linkIcon(
                    'edit', 14, 
                    [
                        'onclick' => Ext::jsAppWidgetLoad('@backend/users/form/view/' . $createdUser['user']['id']),
                        'title'   => 'Редактировать'
                    ]
                );
                echo ' ', $createdUser['user']['username'];
            endif;
        else:
            echo HtmlNav::linkIcon(
                'edit', 14,
                [
                    'onclick' => Ext::jsAppWidgetLoad('@backend/user-profiles/form/view/' . $createdUser['profile']['id']),
                    'title'   => 'Редактировать'
                ]
            );
            echo ' ', $createdUser['profile']['name'];
            if (!empty($createdUser['user']['username'])):
                echo ' ( ';
                echo HtmlNav::linkIcon(
                    'edit', 14,
                    [
                        'onclick' => Ext::jsAppWidgetLoad('@backend/users/form/view/' . $createdUser['user']['id']),
                        'title'   => 'Редактировать'
                    ]
                );
                echo ' ', $createdUser['user']['username'], ')';
            endif;
        endif;
    else:
        echo '[ неизвестно ]';
    endif;
?>
            </span>
        </p>
    </div>
</div>

<div class="row-fluid">
    <div class="col-md-12">
        <h2>Конфигурация расширения</h2>
        <p>
            <label>Назначение:</label> 
<?php if ($use === BACKEND): ?>
            <span class="parameter"><?= Ge::t('app', BACKEND_NAME) ?></span>
<?php else: ?>
<?php if ($use === FRONTEND): ?>
            <span class="parameter"><?= Ge::t('app', FRONTEND_NAME) ?></span>
<?php else: ?>
            <span class="parameter">[ неизвестно ]</span>
<?php endif; endif;  ?>
        </p>
        <p>
            <label>Системное (встроенное):</label> <?= HtmlNav::checkIcon($lock) ?>
        </p>
        <p>
            <label>Имеет настройки:</label> <?= HtmlNav::checkIcon($hasSettings) ?>
        </p>
        <p>
            <label>Идентификатор расширения:</label> 
            <span class="parameter"><?= $id ?></span>
        </p>
        <p>
            <label>Идентификатор в базе данных:</label> 
            <span class="parameter"><?= $rowId ?></span>
        </p>
        <p>
            <label>Пространство имён:</label> 
            <span class="parameter"><?= $namespace ?></span>
        </p>
        <p>
            <label>Имя контроллера по умолчанию:</label> 
            <span class="parameter"><?= $extension->defaultController ?></span>
        </p>

        <h4>Пути</h4>
        <p>
            <label>Локальный путь:</label> 
            <span class="parameter"><?= $path ?></span>
        </p>
        <p>
            <label>Абсолютгый путь:</label> 
            <span class="parameter"><?= $extension->basePath ?></span>
        </p>
        <p>
            <label>Путь к ресурсам:</label> 
            <span class="parameter"><?= $extension->getAssetsPath() ?></span>
        </p>
        <p>
            <label>Путь к скриптам:</label> 
            <span class="parameter"><?= $extension->getRequireUrl() ?></span>
        </p>
    </div>
</div>

<?php if ($install['shortcodes']): ?>
<div class="row-fluid">
    <div class="col-md-12">
        <h2>Используемые шорткоды (shortcode)</h2>
        <p>
            <label>Шорткоды:</label> 
            <span class="parameter">
<?php foreach ($install['shortcodes'] as $index => $name): ?> 
 [<?= $name ?>]
<?php endforeach ?>
            </span>
        </p>

<?php if ($shortcodesConfig = $extension->getConfig()->get('shortcodes', [])): ?>
        <h4>Параметры</h4>
        <table>
            <tr>
                <th width="100px">Имя</th>
                <th>Значение</th>
            </tr>
<?php foreach ($shortcodesConfig as $name => $value): ?>
            <tr>
                <td><?= $name ?></td><td><?= $value ?></td>
            </tr>
<?php endforeach ?>
        </table>
<?php endif ?>
    </div>
</div>
<?php endif ?>

<?php if ($extension->viewManager): ?>
<div class="row-fluid">
    <div class="col-md-12">
        <h2>Отображение модуля</h2>
        <p>
            <label>Идентификатор в шаблоне:</label> 
            <span class="parameter"><?= $extension->viewManager->id ?? '[ неизвестно ]' ?></span>
        </p>
        <p>
            <label>Автозагрузка шаблонов из темы:</label> <?= HtmlNav::checkIcon($extension->viewManager->useTheme) ?>
        </p>
        <p>
            <label>Использование локализации в определении имени файлов шаблонов:</label> <?= HtmlNav::checkIcon($extension->viewManager->useLocalize) ?>
        </p>
        <p>
            <label>Разделитель в имени файлов шаблонов:</label> 
            <span class="parameter">&laquo;<?= $extension->viewManager->localeDelimiter ?>&raquo;</span>
        </p>
        <p>
            <label>Путь к файлам шаблонов:</label> 
            <span class="parameter"><?= $extension->viewManager->basePath ?></span>
        </p>
    </div>
</div>

<?php if ($map = $extension->viewManager->getTempalteMap()): ?>
<div class="row-fluid">
    <div class="col-md-12">
        <h2>Шаблоны</h2>
        <table>
            <tr>
                <th width="100px">Имя</th>
                <th>Путь в карте шаблонов</th>
                <th>Полный путь к файлу шаблона</th>
            </tr>
<?php foreach($map as $name => $path): $filename = $extension->viewManager->getViewFile($name); ?>
            <tr>
                <td><?= $name ?></td>
                <td><?= $path ?></td>
                <td><?= $filename ?: HtmlNav::checkIcon(false) ?></td>
            </tr>
<?php endforeach ?>
        </table>
    </div>
</div>
<?php endif ?>

<?php if ($renderers = $extension->viewManager->getRenderers()): ?>
<div class="row-fluid">
    <div class="col-md-12">
        <h2>Визуализаторы (рендеры)</h2>
        <table>
            <tr>
                <th width="100px">Имя</th>
                <th>Класс рендера</th>
            </tr>
<?php foreach ($renderers as $name => $renderer): $className = $extension->viewManager->makeClassNameRenderer($name); ?>
            <tr>
                <td><?= $name ?></td>
                <td><?= $className ?></td>
            </tr>
<?php endforeach ?>
        </table>
    </div>
</div>
<?php endif ?>

<?php if ($assets = $extension->viewManager->assets): ?>
<div class="row-fluid">
    <div class="col-md-12">
        <h2>Подключаемые скрипты</h2>
<?php if (!empty($assets['packages'])): ?>
        <h4>Пакеты скриптов:</h4>
        <ul class="none">
<?php foreach ($assets['packages'] as $name => $package): ?>
            <li>
                <h4><?= $name ?></h4>
                <ul>
<?php if (isset($package['position'])): ?>
                    <li><label>позиция:</label> <?= $package['position'] ?></li>
<?php endif ?>
<?php if (isset($package['core'])): ?>
                    <li><label>ядро:</label> <?= HtmlNav::checkIcon($package['core']) ?></li>
<?php endif ?>
<?php if (isset($package['custom'])): ?>
                    <li><label>custom:</label> <?= HtmlNav::checkIcon($package['custom']) ?></li>
<?php endif ?>
<?php if (!empty($package['js'])): ?>
                    <li>
                        <label>javascript:</label><br />
<?
foreach($package['js'] as $filename => $position):
    echo (is_numeric($filename) ? $position : $filename), '<br />';
endforeach
?>
                    </li>
<?php endif ?>
<?php if (!empty($package['css'])): ?>
                    <li>
                        <label>stylesheat:</label><br />
<?
foreach ($package['css'] as $filename => $position):
    echo (is_numeric($filename) ? $position : $filename), '<br />';
endforeach
?>
                    </li>
<?php endif ?>
                </ul>
            </li>
<?php endforeach ?>
        </ul>
<?php endif ?>
    </div>
</div>
<?php endif ?>
<?php endif ?>

<div class="row-fluid">
    <div class="col-md-12">
        <h2>Права доступа (разрешения)</h2>
<?php if ($permissions && $roles): ?>
        <table class="compact">
            <tr>
                <th width="220px" rowspan="2">Права доступа<br>-<br>Роли пользователей</th>
<?php foreach ($permissions as $permission => $name): ?>
                <th width="140px" style="color:#217346;font-size:17px;padding:3px;background-color:#e4e4e4"><?= $permission ?></th>
<?php endforeach ?>
            </tr>
            <tr>
<?php foreach ($permissions as $permission => $name): ?>
                <th valign="top">
                    <div style="color:#3e79b4;font-size:12px;text-transform:uppercase"><?= Str::ellipsis($name[0], 0, 16) ?></div>
                    <div><?= $name[1] ?></div>
                </th>
<?php endforeach ?>
            </tr>
<?php foreach ($roles as $index => $role): ?>
            <tr>
                <td><?= $role['role'] ?></td>
<?php foreach ($permissions as $permission => $name): ?>
                <td align="center"><?= HtmlNav::checkIcon(in_array($permission,  $role['permissions'])) ?></td>
<?php endforeach ?>
            </tr>
<?php endforeach ?>
        </table>
<?php else: ?>
        <span class="parameter">[ не применяются ]</span>
<?php endif ?>
    </div>
</div>