<?php
use Ge\Panel\Helper\Ext;
use Ge\Panel\Helper\HtmlNavigator as HtmlNav;
?>
<div class="container-fluid">
    <div class="row-fluid">
        <h1>Информация о плагине: <span>&laquo;<?= $name ?>&raquo;</span></h1>
        <div class="icon" style="background-image: url(<?= $icon ?>)">
            <p><?= $description ?></p>
        </div>
    </div>
</div>

<?php if ($version) : ?>
<div class="row-fluid">
    <div class="col-md-12">
        <h2>Версия плагина</h2>
        <p>
            <label>Версия:</label>  
            <span class="parameter"><?= $version['version'] ?: '[ неизвестно ]' ?></span>
        </p>
        <p>
            <label>Дата:</label>  
            <span class="parameter"><?= $version['versionDate'] ? Ge::$app->formatter->toDate($version['versionDate']) : '[ неизвестно ]' ?></span>
        </p>
        <p>
            <label>Страница плагина:</label> 
<?php if ($version['url']): ?>
            <span class="parameter"><a target="_blank" href="<?= $version['url'] ?>"><?= $version['url'] ?></a></span>
<?php else: ?>
            <span class="parameter">[ неизвестно ]</span>
<?php endif ?>
        </p>
        <p>
            <label>Страница</label> 
            <a target="_blank" href="#" onclick="<?= Ext::jsAppWidgetLoad('@backend/marketplace/catalog/component/view', ['id' => $id]) ?>;return false">в кателоге Маркетплейс</a>
        </p>

        <h2>Автор</h2>
        <p>
            <label>Имя автора:</label> 
            <span class="parameter"><?= $version['author'] ?: '[ неизвестно ]' ?></span>
        </p>
        <p>
            <label>Страница автора:</label>
<?php if ($version['authorUrl']): ?>
            <span class="parameter"><a target="_blank" href="<?= $version['authorUrl'] ?>"><?= $version['authorUrl'] ?></a></span>
<?php else: ?>
            <span class="parameter">[ неизвестно ]</span>
<?php endif ?>
        </p>
        <p>
            <label>E-mail:</label> 
            <span class="parameter"><?= $version['email'] ?: '[ неизвестно ]' ?></span>
        </p>

        <h2>Лицензия</h2>
        <p>
<?php if ($version['licenseUrl']): ?>
            <span class="parameter"><a href="<?= $version['licenseUrl'] ?>"><?= $version['license'] ?></a></span>
<?php else: ?>
            <span class="parameter"><?= $version['license'] ?: '[ неизвестно ]' ?></span>
<?php endif ?>
        </p>
    </div>
</div>
<?php endif ?>

<div class="row-fluid">
    <div class="col-md-12">
        <h2>Состояние плагина</h2>
        <p>
            <label>Доступен:</label> <?= HtmlNav::checkIcon($enabled, 18) ?>
        </p>
    </div>
</div>

<div class="row-fluid">
    <div class="col-md-12">
        <h2>Плагин установлен</h2>
        <p>
            <label>Дата и время:</label> 
            <span class="parameter"><?= $createdDate ?: '[ неизвестно ]' ?></span>
        </p>
        <p>
            <label>Пользователь:</label> 
            <span class="parameter">
<?php
    if ($createdUser): 
        if (empty($createdUser['profile']['name'])):
            if (empty($createdUser['user']['username'])):
                echo '[ неизвестно ]';
            else:
                echo HtmlNav::linkIcon(
                    'edit', 14, 
                    [
                        'onclick' => Ext::jsAppWidgetLoad('@backend/users/form/view/' . $createdUser['user']['id']),
                        'title'   => 'Редактировать'
                    ]
                );
                echo ' ', $createdUser['user']['username'];
            endif;
        else:
            echo HtmlNav::linkIcon(
                'edit', 14,
                [
                    'onclick' => Ext::jsAppWidgetLoad('@backend/user-profiles/form/view/' . $createdUser['profile']['id']),
                    'title'   => 'Редактировать'
                ]
            );
            echo ' ', $createdUser['profile']['name'];
            if (!empty($createdUser['user']['username'])):
                echo ' ( ';
                echo HtmlNav::linkIcon(
                    'edit', 14,
                    [
                        'onclick' => Ext::jsAppWidgetLoad('@backend/users/form/view/' . $createdUser['user']['id']),
                        'title'   => 'Редактировать'
                    ]
                );
                echo ' ', $createdUser['user']['username'], ')';
            endif;
        endif;
    else:
        echo '[ неизвестно ]';
    endif;
?>
            </span>
        </p>
    </div>
</div>

<div class="row-fluid">
    <div class="col-md-12">
        <h2>Конфигурация плагина</h2>
        <p>
            <label>Имеет настройки:</label> <?= HtmlNav::checkIcon($hasSettings) ?>
        </p>
        <p>
            <label>Идентификатор плагина:</label> 
            <span class="parameter"><?= $id ?></span>
        </p>
        <p>
            <label>Идентификатор в базе данных:</label> 
            <span class="parameter"><?= $rowId ?></span>
        </p>
        <p>
            <label>Пространство имён:</label> 
            <span class="parameter"><?= $namespace ?></span>
        </p>

        <h4>Пути</h4>
        <p>
            <label>Локальный путь:</label> 
            <span class="parameter"><?= $path ?></span>
        </p>
        <p>
            <label>Абсолютгый путь:</label> 
            <span class="parameter"><?= Ge::$app->modulePath . $path ?></span>
        </p>
    </div>
</div>