<?php
use Ge\Panel\Helper\Ext;
use Ge\Panel\Helper\HtmlNavigator as HtmlNav;
?>
<div class="container-fluid">
    <div class="row-fluid">
        <h1>Information about the widget: <span>&laquo;<?= $name ?>&raquo;</span></h1>
        <div class="icon" style="background-image: url(<?= $icon ?>)">
            <p><?= $description ?></p>
        </div>
    </div>
</div>

<?php if ($version) : ?>
<div class="row-fluid">
    <div class="col-md-12">
        <h2>Widget version</h2>
        <p>
            <label>Version:</label>  
            <span class="parameter"><?= $version['version'] ?: '[ unknown ]' ?></span>
        </p>
        <p>
            <label>Date:</label>  
            <span class="parameter"><?= $version['versionDate'] ? Ge::$app->formatter->toDate($version['versionDate']) : '[ unknown ]' ?></span>
        </p>
        <p>
            <label>Widget page:</label> 
<?php if ($version['url']): ?>
            <span class="parameter"><a target="_blank" href="<?= $version['url'] ?>"><?= $version['url'] ?></a></span>
<?php else: ?>
            <span class="parameter">[ unknown ]</span>
<?php endif ?>
        </p>
        <p>
            <label>Page</label> 
            <a target="_blank" href="#" onclick="<?= Ext::jsAppWidgetLoad('@backend/marketplace/catalog/component/view', ['id' => $id]) ?>;return false">in the Marketplace catalog</a>
        </p>

        <h2>Author</h2>
        <p>
            <label>Author's name:</label> 
            <span class="parameter"><?= $version['author'] ?: '[ unknown ]' ?></span>
        </p>
        <p>
            <label>Author page:</label>
<?php if ($version['authorUrl']): ?>
            <span class="parameter"><a target="_blank" href="<?= $version['authorUrl'] ?>"><?= $version['authorUrl'] ?></a></span>
<?php else: ?>
            <span class="parameter">[ unknown ]</span>
<?php endif ?>
        </p>
        <p>
            <label>E-mail:</label> 
            <span class="parameter"><?= $version['email'] ?: '[ unknown ]' ?></span>
        </p>

        <h2>License</h2>
        <p>
<?php if ($version['licenseUrl']): ?>
            <span class="parameter"><a href="<?= $version['licenseUrl'] ?>"><?= $version['license'] ?></a></span>
<?php else: ?>
            <span class="parameter"><?= $version['license'] ?: '[ unknown ]' ?></span>
<?php endif ?>
        </p>
    </div>
</div>
<?php endif ?>

<div class="row-fluid">
    <div class="col-md-12">
        <h2>Widget status</h2>
        <p>
            <label>Enabled:</label> <?= HtmlNav::checkIcon($enabled, 18) ?>
        </p>
    </div>
</div>

<div class="row-fluid">
    <div class="col-md-12">
        <h2>Widget installed</h2>
        <p>
            <label>Date and time:</label> 
            <span class="parameter"><?= $createdDate ?: '[ unknown ]' ?></span>
        </p>
        <p>
            <label>User:</label> 
            <span class="parameter">
<?php
    if ($createdUser): 
        if (empty($createdUser['profile']['name'])):
            if (empty($createdUser['user']['username'])):
                echo '[ unknown ]';
            else:
                echo HtmlNav::linkIcon(
                    'edit', 14, 
                    [
                        'onclick' => Ext::jsAppWidgetLoad('@backend/users/form/view/' . $createdUser['user']['id']),
                        'title'   => 'Edit'
                    ]
                );
                echo ' ', $createdUser['user']['username'];
            endif;
        else:
            echo HtmlNav::linkIcon(
                'edit', 14,
                [
                    'onclick' => Ext::jsAppWidgetLoad('@backend/user-profiles/form/view/' . $createdUser['profile']['id']),
                    'title'   => 'Edit'
                ]
            );
            echo ' ', $createdUser['profile']['name'];
            if (!empty($createdUser['user']['username'])):
                echo ' ( ';
                echo HtmlNav::linkIcon(
                    'edit', 14,
                    [
                        'onclick' => Ext::jsAppWidgetLoad('@backend/users/form/view/' . $createdUser['user']['id']),
                        'title'   => 'Edit'
                    ]
                );
                echo ' ', $createdUser['user']['username'], ')';
            endif;
        endif;
    else:
        echo '[ unknown ]';
    endif;
?>
            </span>
        </p>
    </div>
</div>

<div class="row-fluid">
    <div class="col-md-12">
        <h2>Widget configuration</h2>
        <p>
            <label>Has settings:</label> <?= HtmlNav::checkIcon($hasSettings) ?>
        </p>
        <p>
            <label>Widget ID:</label> 
            <span class="parameter"><?= $id ?></span>
        </p>
        <p>
            <label>ID in the database:</label> 
            <span class="parameter"><?= $rowId ?></span>
        </p>
        <p>
            <label>Namespace:</label> 
            <span class="parameter"><?= $namespace ?></span>
        </p>

        <h4>Path</h4>
        <p>
            <label>Local path:</label> 
            <span class="parameter"><?= $path ?></span>
        </p>
        <p>
            <label>Base path:</label> 
            <span class="parameter"><?= Ge::$app->modulePath . $path ?></span>
        </p>
    </div>
</div>